### ISSUE TITLE
Getting "SyntaxError: Assigning to rvalue" when writing to process.env.NODE_ENV

### ISSUE THREAD

**Issue by joshwilsonvu** [preconstruct/preconstruct#267]
Hi,

Trying to write to `process.env.NODE_ENV` gives an obscure error message:

```
🎁 error @mm/cli Error: Assigning to rvalue
🎁 error @mm/cli     at error (/Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:5400:30)
🎁 error @mm/cli     at Module.error (/Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:9820:16)
🎁 error @mm/cli     at tryParse (/Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:9713:23)
🎁 error @mm/cli     at Module.setSource (/Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:10076:33)
🎁 error @mm/cli     at /Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:12362:20
🎁 error @mm/cli     at processTicksAndRejections (internal/process/task_queues.js:93:5)
🎁 error @mm/cli     at async Promise.all (index 0)
🎁 error @mm/cli     at async Promise.all (index 0)
🎁 error @mm/cli     at async Promise.all (index 0) {
🎁 error @mm/cli   code: 'PARSE_ERROR',
🎁 error @mm/cli   parserError: SyntaxError: Assigning to rvalue (114:4)
🎁 error @mm/cli       at Object.pp$4.raise (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:2836:15)
🎁 error @mm/cli       at Object.pp$2.toAssignable (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:1693:14)
🎁 error @mm/cli       at Object.pp$3.parseMaybeAssign (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:1973:49)
🎁 error @mm/cli       at Object.pp$3.parseExpression (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:1933:21)
🎁 error @mm/cli       at Object.pp$1.parseStatement (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:877:47)
🎁 error @mm/cli       at Object.parseStatement (/Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:11825:30)
🎁 error @mm/cli       at Object.pp$1.parseBlock (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:1161:23)
🎁 error @mm/cli       at Object.pp$1.parseStatement (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:845:36)
🎁 error @mm/cli       at Object.parseStatement (/Users/Josh/WebstormProjects/mm/node_modules/rollup/dist/shared/node-entry.js:11825:30)
🎁 error @mm/cli       at Object.pp$1.parseIfStatement (/Users/Josh/WebstormProjects/mm/node_modules/acorn/dist/acorn.js:991:51) {
🎁 error @mm/cli     pos: 3397,
🎁 error @mm/cli     loc: Position { line: 114, column: 4 },
🎁 error @mm/cli     raisedAt: 3411
🎁 error @mm/cli   },
🎁 error @mm/cli   pos: 3397,
🎁 error @mm/cli   loc: {
🎁 error @mm/cli     column: 4,
🎁 error @mm/cli     file: '/Users/Josh/WebstormProjects/mm/packages/cli/src/index.js',
🎁 error @mm/cli     line: 100
🎁 error @mm/cli   },
🎁 error @mm/cli   frame: ' 98:   } else {\n' +
🎁 error @mm/cli     ' 99:     // Serve the client bundle in development mode, watching for changes\n' +
🎁 error @mm/cli     '100:     process.env.NODE_ENV = "development";\n' +
🎁 error @mm/cli     '         ^\n' +
🎁 error @mm/cli     '101:     const bundler = new Bundler(paths.appIndexHtml, {\n' +
🎁 error @mm/cli     '102:       outDir: paths.appBuild,',
🎁 error @mm/cli   watchFiles: [ '/Users/Josh/WebstormProjects/mm/packages/cli/src/index.js' ]
🎁 error @mm/cli }
🎁 info If want to learn more about the above error, check https://preconstruct.tools/errors
🎁 info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
error Command failed with exit code 1.
```
I totally understand how this happens, with `process.env.NODE_ENV` being replaced with a string constant, but it was hard to tell from the message and it's not mentioned in https://preconstruct.tools/errors. Maybe that page could add this as an entry?

Thanks.

**Comment by chenxsan** [comment]
Got the same problem when trying to set `process.env.NODE_ENV` to `production`.

**Comment by joshwilsonvu** [comment]
@chenxsan That's because preconstruct replaces the string `process.env.NODE_ENV` in your code with `"production"` or `"development"`. It's nice because it lets you and your dependencies read `process.env.NODE_ENV` even in the browser, but you can get around it with the other syntax. But be aware that other parts of your code or dependency code may not see the change you made, only the replacement string literal value.

**Comment by mitchellhamilton** [comment]
Happy to accept a PR either fixing this issue(assuming that it doesn't add a significant performance cost(i.e. it can't use an extra Babel transform for this)) or adding it to docs
