### ISSUE TITLE
importing font error "Unexpected character '' 

### ISSUE THREAD

**Issue by Joshhw** [preconstruct/preconstruct#289]
Im trying to import a local font file like so:
```
import { css, createGlobalStyle } from 'styled-components';
import FruitgerLight from '../assets/fonts/Frutiger/FrutigerLTW02-45Light.ttf';

const GlobalStyle = createGlobalStyle`
@font-face {
  font-family: 'Frutiger-Light';
  src: url(${FruitgerLight});
}`
```

This is my package:
```
{
  "name": "lnk-ui-react",
  "version": "3.2.0",
  "license": "ISC",
  "main": "dist/lnk-ui-react.cjs.js",
  "module": "dist/lnk-ui-react.esm.js",
  "scripts": {
    "styleguide": "styleguidist server",
    "styleguide:build": "styleguidist build",
    "start": "yarn styleguide",
    "build": "yarn styleguide:build",
    "prepublish": "preconstruct build",
    "typecheck": "tsc --noEmit",
    "test": "yarn typecheck && jest",
    "test:changed": "jest -o -i",
    "test:watch": "jest --watch",
    "prettier:fix": "prettier --write '{src,test,acceptance-tests}/**/*.{js,jsx,ts,tsx}'",
    "prettier:diff": "prettier -l '{src,test,acceptance-tests}/**/*.{js,jsx,ts,tsx}'"
  },
  "browserslist": [
    ">1%",
    "last 4 versions",
    "Firefox ESR",
    "not ie < 11",
    "not dead"
  ],
  "devDependencies": {
    "@babel/cli": "^7.10.1",
    "@babel/core": "^7.10.1",
    "@babel/plugin-proposal-class-properties": "^7.10.1",
    "@babel/plugin-proposal-object-rest-spread": "^7.10.1",
    "@babel/preset-env": "^7.10.1",
    "@babel/preset-react": "^7.10.1",
    "@babel/preset-typescript": "^7.10.1",
    "@material-ui/core": "^4.7.3",
    "@preconstruct/cli": "^1.1.14",
    "@types/enquire.js": "^2.1.2",
    "@types/enzyme": "^3.10.5",
    "@types/enzyme-adapter-react-16": "^1.0.6",
    "@types/jest": "^26.0.0",
    "@types/prop-types": "^15.7.3",
    "@types/react": "^16.9.36",
    "@types/react-dom": "^16.9.8",
    "@types/react-select": "^3.0.13",
    "@types/react-stickynode": "^3.0.0",
    "@types/styled-components": "^5.1.0",
    "@types/styled-system": "^5.1.9",
    "babel-jest": "^25.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-styled-components": "^1.10.7",
    "enquire.js": "^2.1.6",
    "enzyme": "^3.11.0",
    "enzyme-adapter-react-16": "^1.15.2",
    "file-loader": "^1.1.11",
    "jest": "^26.0.1",
    "prettier": "^2.0.5",
    "raf": "^3.4.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-is": "^16.13.1",
    "react-select": "^3.1.0",
    "react-stickynode": "^3.0.3",
    "react-styleguidist": "^11.0.8",
    "styled-components": "^5.1.0",
    "typescript": "^3.9.5",
    "webpack": "^4.43.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  },
  "dependencies": {
    "@styled-system/prop-types": "^5.1.5",
    "core-js": "3.6.5",
    "prop-types": "^15.7.2",
    "react-onclickoutside": "^6.8.0",
    "styled-system": "^5.1.5"
  },
  "peerDependencies": {
    "@material-ui/core": "^4.7.3",
    "enquire.js": "^2.1.6",
    "react": "^16.8.0",
    "react-dom": "^16.8.0",
    "react-select": "^3.1.0",
    "react-stickynode": "^3.0.3",
    "styled-components": "^5.1.0"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx,mjs}"
    ],
    "collectCoverage": true,
    "coverageDirectory": "coverage",
    "setupFiles": [
      "<rootDir>/config/jest/polyfills.js"
    ],
    "setupFilesAfterEnv": [
      "<rootDir>/config/jest/setupTests.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,ts,tsx,mjs}"
    ],
    "testEnvironment": "jsdom",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|ts|tsx)$": "babel-jest"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleFileExtensions": [
      "web.js",
      "mjs",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "ts",
      "tsx"
    ]
  }
}
```

My webpack config is so:
```
const path = require('path');

const srcDir = path.resolve(__dirname, 'src');

module.exports = {
  resolve: {
    modules: [srcDir, 'node_modules'],
    alias: {
      'lnk-ui-react': path.join(__dirname, 'src'), // self reference
    },
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx|ts|tsx)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
          },
        ],
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.(png|jpg|jpeg|)$/,
        include: srcDir,
        use: ['file-loader'],
      },
      {
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        include: srcDir,
        use: ['file-loader'],
      },
    ],
  },
};

```

and this is the error I'm getting:

```
$ preconstruct build
🎁 info building bundles!
🎁 error lnk-ui-react Error: Unexpected character '' (Note that you need plugins to import files that are not JavaScript)
🎁 error lnk-ui-react     at error (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:5400:30)
🎁 error lnk-ui-react     at Module.error (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:9824:16)
🎁 error lnk-ui-react     at tryParse (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:9717:23)
🎁 error lnk-ui-react     at Module.setSource (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:10080:33)
🎁 error lnk-ui-react     at /Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:12366:20
🎁 error lnk-ui-react     at async Promise.all (index 3)
🎁 error lnk-ui-react     at async Promise.all (index 0)
🎁 error lnk-ui-react     at async Promise.all (index 0)
🎁 error lnk-ui-react     at async Promise.all (index 0)
🎁 error lnk-ui-react     at async Promise.all (index 0) {
🎁 error lnk-ui-react   code: 'PARSE_ERROR',
🎁 error lnk-ui-react   parserError: SyntaxError: Unexpected character '' (1:0)
🎁 error lnk-ui-react       at Object.pp$4.raise (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/node_modules/acorn/dist/acorn.js:2927:15)
🎁 error lnk-ui-react       at Object.pp$9.getTokenFromCode (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/node_modules/acorn/dist/acorn.js:4695:10)
🎁 error lnk-ui-react       at Object.pp$9.readToken (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/node_modules/acorn/dist/acorn.js:4409:17)
🎁 error lnk-ui-react       at Object.pp$9.nextToken (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/node_modules/acorn/dist/acorn.js:4400:17)
🎁 error lnk-ui-react       at Object.parse (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/node_modules/acorn/dist/acorn.js:554:10)
🎁 error lnk-ui-react       at Function.parse (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/node_modules/acorn/dist/acorn.js:578:37)
🎁 error lnk-ui-react       at tryParse (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:9707:23)
🎁 error lnk-ui-react       at Module.setSource (/Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:10080:33)
🎁 error lnk-ui-react       at /Users/jd/Documents/code/lnk/lnk-ui-react/node_modules/rollup/dist/shared/node-entry.js:12366:20
🎁 error lnk-ui-react       at async Promise.all (index 3) {
🎁 error lnk-ui-react     pos: 0,
🎁 error lnk-ui-react     loc: Position { line: 1, column: 0 },
🎁 error lnk-ui-react     raisedAt: 0
🎁 error lnk-ui-react   },
🎁 error lnk-ui-react   pos: 0,
🎁 error lnk-ui-react   loc: {
🎁 error lnk-ui-react     column: 0,
🎁 error lnk-ui-react     file: '/Users/jd/Documents/code/lnk/lnk-ui-react/src/assets/fonts/Frutiger/FrutigerLTW02-45Light.ttf',
🎁 error lnk-ui-react     line: 1
🎁 error lnk-ui-react   },
🎁 error lnk-ui-react   frame: '1: \x00\x01\x00\x00\x00\x10\x01\x00\x00\x04\x00\x00GPOS��\x16�\x00\x00\x01\f\x00\x00\bLOS/2e��}\x00\x00\tX\x00\x00\x00`VDMXmju\x0B\x00\x00\t�\x00\x00\x05�cmap����\x00\x00\x0F�\x00\x00\x04xcvt \n' +
🎁 error lnk-ui-react     '   ^\n' +
🎁 error lnk-ui-react     '2: �\x0Ey\x00\x00\x14\x10\x00\x00\x00�fpgm,���\x00\x00\x14�\x00\x00\x07�gasp\x00\b\x00\x1B\x00\x00\x1C`\x00\x00\x00\fglyfx�\x13\x11\x00\x00\x1Cl\x00\x00��head\x05弄\x00\x00�@\x00\x00\x006hhea\x06�\x07�\x00\x00�x\x00\x00\x00$hmtx�C�\x00\x00��\x00\x00\x06\flocaP�r�\x00\x00��\x00\x00\x03\bmaxp\x02�\x01-\x00\x00��\x00\x00\x00 name��N\x1A\x00\x00��\x00\x00\x1Cqpost��\x002\x00\x00�D\x00\x00\x00 prep3e�"\x00\x00�d\x00\x00\x01\x10\x00\x01\x00\x00\x00\n' +
🎁 error lnk-ui-react     '3: \x00d\x00�\x00\x01latn\x00\b\x00"\x00\x05AFK \x00*DEU \x002NLD \x00:ROM \x00BTRK \x00J\x00\x00��\x00\x01\x00\x00\x00\x00��\x00\x01\x00\x01\x00\x00��\x00\x01\x00\x02\x00\x00��\x00\x01\x00\x03\x00\x00��\x00\x01\x00\x04\x00\x00��\x00\x01\x00\x05\x00\x06kern\x00&kern\x00,kern\x002kern\x008kern\x00>kern\x00D\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x01\x00\x00\x00\x01\x00\x04\x00\t\x00\x00\x00\x02\x00',
🎁 error lnk-ui-react   watchFiles: [
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/utils/themes.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/utils/linkStyle.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/types/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Banner/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Button/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Checkbox/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Input/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Footer/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/lnk/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Loader/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Panel/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Dropdown/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/CustomRadio/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Modal/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/StatusPill/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/ExtendedButton/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Tooltip/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/LinearLoader/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Tabs/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Select/index.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Icon/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Sidebar/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/NavigationPanel/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/CountBubble/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Header/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/StatusMarker/index.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/utils/fonts.ts',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Panel/Panel.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/StatusPill/StatusPill.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/ExtendedButton/ExtendedButton.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Tooltip/InfoTooltip.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Tooltip/Tooltip.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/LinearLoader/LinearLoader.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Tabs/Tabs.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Select/Select.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Icon/Icon.tsx',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Sidebar/Sidebar.tsx',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/NavigationPanel/NavigationPanel.tsx',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Header/Header.tsx',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/StatusMarker/StatusMarker.tsx',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/CountBubble/CountBubble.tsx',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Loader/Loader.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Dropdown/Dropdown.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/CustomRadio/CustomRadio.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/components/Modal/Modal.js',
🎁 error lnk-ui-react     '/Users/jd/Documents/code/lnk/lnk-ui-react/src/assets/fonts/Frutiger/FrutigerLTW02-45Light.ttf'
🎁 error lnk-ui-react   ]
🎁 error lnk-ui-react }
```

**Comment by saq194** [comment]
ggggg

**Comment by mitchellhamilton** [comment]
Thanks for the issue! Preconstruct doesn't support things like importing font files(and similar things like css files and etc.) because there isn't a standardized meaning for "importing a font file" that works across Node and various bundlers. You can ship the font file in your package and provide a way for consumers to pass in a url to your code though.
