### ISSUE TITLE
SyntaxError: Unexpected token u in JSON at position 0 on CI 

### ISSUE THREAD

**Issue by sarahbethfederman** [preconstruct/preconstruct#325]
I've got a pretty obtuse error that's only occurring on CI. Not sure if it's a preconstruct issue, but I'm not really sure where to look. If it's relevant, typography is the last package in my repo (alphabetically), and all of the packages except for typography seem to be getting built correctly. Any idea where to dig?
```
$ preconstruct build
--
  | 🎁 info building bundles!
  | 🎁 error @lendi-ui/typography { SyntaxError: Unexpected token u in JSON at position 0
  | 🎁 error @lendi-ui/typography     at JSON.parse (<anonymous>)
  | 🎁 error @lendi-ui/typography     at tryDirectoryWithPackageJson (/var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:105044:51)
  | 🎁 error @lendi-ui/typography     at tryGetModuleNameAsNodeModule (/var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:105012:30)
  | 🎁 error @lendi-ui/typography     at /var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:104808:88
  | 🎁 error @lendi-ui/typography     at Object.mapDefined (/var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:712:30)
  | 🎁 error @lendi-ui/typography     at Object.getModuleSpecifiers (/var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:104808:29)
  | 🎁 error @lendi-ui/typography     at getSpecifierForModuleSymbol (/var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:39583:62)
  | 🎁 error @lendi-ui/typography     at /var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:39443:39
  | 🎁 error @lendi-ui/typography     at Array.map (<anonymous>)
  | 🎁 error @lendi-ui/typography     at getSymbolChain (/var/lib/buildkite-agent/builds/buildkite-workers-general-management-i-0abc5c2f8ac3b193f-1/lendi-pty-ltd/lui/node_modules/typescript/lib/typescript.js:39441:58)
  | 🎁 error @lendi-ui/typography   code: 'PLUGIN_ERROR',
  | 🎁 error @lendi-ui/typography   plugin: 'typescript-declarations',
  | 🎁 error @lendi-ui/typography   hook: 'generateBundle' }
  | 🎁 info If want to learn more about the above error, check https://preconstruct.tools/errors
  | 🎁 info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
  | error Command failed with exit code 1.
```

**Comment by sarahbethfederman** [comment]
So oddly enough this seems to only trigger when we have exactly more than 809 entrypoints, and it doesn't care what is in them. Gonna see if I can reproduce

**Comment by sarahbethfederman** [comment]
Still knocking head on wall with this, but we've isolated it to only occurring on linux machines and mac is fine. Working with our platform team to try and figure out where they deviate

**Comment by sarahbethfederman** [comment]
So its running fine in a docker container. Not sure why it doesnt run properly on linux, but its working now
