### ISSUE TITLE
The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../../dist/index.d.ts".

### ISSUE THREAD

**Issue by alii** [preconstruct/preconstruct#443]
Honestly, I have no idea what is going on here or how to fix it. I've found another issue on GitHub with the same error message but it looks like that was fixed & it was also a while ago: https://github.com/egoist/rollup-plugin-postcss/issues/250

This branch on the repo alii/nextkit seems to be running into the issue: https://github.com/alii/nextkit/tree/0b35d155e5902a9e76421b12da1a709479d4e9a7

It's probably something wrong in my setup but I've scoured through and can't seem to see anything out of the normal. Preconstruct is an amazing tool and has been flawless up until now 😧 thank you for the hard work!

![image](https://user-images.githubusercontent.com/25351731/150717129-705f1cc7-6e00-4ff0-a190-4abcf1d7cd89.png)

**Comment by alii** [comment]
Update, seemed to have resolved it by changing `module` to `commonjs` in `tsconfig.json`. Perhaps I should still keep this open as the error message is rather poor 😄

**Comment by skarab42** [comment]
The same error here in a monorepo, solved by removing `outDir` setting in `tsconfig.json`.

**Comment by mycroes** [comment]
Experiencing same issue, in a monorepo. Removing `outDir` and `declarationDir` does allow `preconstruct build` to complete, but that litters my source tree with `.js` and `.d.ts` files during `tsc -b`, so that's not a valid workaround. I'm actually converting multiple repositories to preconstruct and this is the first where I'm having any issues. As far as I can see there's no difference between the repositories as far as preconstruct is considered, even dependency versions are equal (except for chalk).

**Comment by mycroes** [comment]
Further details of my exact case:
I'm getting the following error:
```
🎁 info building bundles!
🎁 error @vlc/admin Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "..\..\..\build\types\packages\admin\src\index.d.ts".
🎁 error @vlc/admin     at error (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\rollup\dist\shared\rollup.js:198:30)
🎁 error @vlc/admin     at FileEmitter.emitFile (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\rollup\dist\shared\rollup.js:22466:24)
🎁 error @vlc/admin     at C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:1510:14
🎁 error @vlc/admin     at Array.map (<anonymous>)
🎁 error @vlc/admin     at Object.generateBundle (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:1508:43)
🎁 error @vlc/admin     at async Bundle.generate (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\rollup\dist\shared\rollup.js:15927:9)
🎁 error @vlc/admin     at async C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\rollup\dist\shared\rollup.js:23833:27
🎁 error @vlc/admin     at async catchUnfinishedHookActions (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\rollup\dist\shared\rollup.js:23247:20)
🎁 error @vlc/admin     at async C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:2427:18
🎁 error @vlc/admin     at async Promise.all (index 0)
🎁 error @vlc/admin     at async Promise.all (index 1)
🎁 error @vlc/admin     at async buildPackage (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:2420:17)
🎁 error @vlc/admin     at async retryableBuild (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:2443:5)
🎁 error @vlc/admin     at async C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:2475:9
🎁 error @vlc/admin     at async Promise.all (index 0)
🎁 error @vlc/admin     at async build (C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:2473:5)
🎁 error @vlc/admin     at async C:\Users\michaelc\Documents\Projects\VLC\VLC.Infrastructure.Web.Admin\node_modules\@preconstruct\cli\cli\dist\cli.cjs.dev.js:2692:11 {
🎁 error @vlc/admin   code: 'PLUGIN_ERROR',
🎁 error @vlc/admin   pluginCode: 'VALIDATION_ERROR',
🎁 error @vlc/admin   plugin: 'typescript-declarations',
🎁 error @vlc/admin   hook: 'generateBundle'
🎁 error @vlc/admin }
🎁 info If you want to learn more about the above error, check https://preconstruct.tools/errors
🎁 info If the error is not there and you want to learn more about it, open an issue at https://github.com/preconstruct/preconstruct/issues/new
```

My `tsconfig.json` is as follows:
```
{
  "extends": "../../../tsconfig.base.json",
  "compilerOptions": {
    "baseUrl": ".",
    "rootDir": "./src",
    "module": "CommonJS",
    "outDir": "build/cjs",
    "declarationDir": "build/types"
  },
  "include": [
   "src"
  ]
}
```

The referenced `tsconfig.base.json` is:
```
{
  "extends": "@tsconfig/node18-strictest/tsconfig.json",
  "compilerOptions": {
    "composite": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "jsxImportSource": "@emotion/react",
    "exactOptionalPropertyTypes": false,
    "resolveJsonModule": true
  }
}
```

My repository structure:
- /
  - package.json
  - tsconfig.json
  - tsconfig.base.json
  - src/
    - packages/
      - admin/
        - src/
          - index.ts
          - ...
        - package.json
        - tsconfig.json
  
I have a very similar structure in other repositories (just without the root `src/` directory, where it works without issues. I'll update later if that makes any difference to the current repository.

**Comment by mycroes** [comment]
Just tested by moving my packages from `src/packages/` to just `packages/`, that fixes this problem. My guess is there's a directory discovery that doesn't work as intended. @alii @skarab42 do you guys also have a `src/` directory somewhere between the workspace root and the package directory?

**Comment by mycroes** [comment]
You're welcome, thanks for preconstruct and emotion!
